server:
  servlet:
    context-path: /wallet-history
  port: 8081

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/"
      path-mapping:
        health: "health"
        info: "info"

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5